version: '3.8'
services:
  database:
    container_name: green-screen-postgres
    image: postgres:16.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: green-screen-postgres
      POSTGRES_PASSWORD: password
volumes:
  data:
