////addSbtPlugin("org.typelevel" % "sbt-tpolecat" % "0.5.1")
//addSbtPlugin("org.scoverage" % "sbt-scoverage" % "2.0.5")
//addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.4")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.5.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")